
# Get all books
GET http://localhost:8080/api/books/
###

# Get specific book
GET http://localhost:8080/api/books/1111111111
###

# Not Exists Book
GET http://localhost:8080/api/books/1
###

# Create Book if not exists 

POST http://localhost:8080/api/books/ 
Content-Type: application/json; charset=utf-8

{
    "Title": "Go learn", 
    "Author" : "Parvin Zahedi", 
    "ISBN": "3333333333"
}
###

#Don't create Book if already exists 

POST http://localhost:8080/api/books/ 
Content-Type: application/json; charset=utf-8

{
    "Title": "Go learn", 
    "Author" : "Parvin Zahedi", 
    "ISBN": "1111111111"
}